# This file is used for continuous integration

# add an image below later if needed
image: node:20-alpine

stages:
  # tests concurrently with lint and unit tests
  - concurChecks
  - deploy

# install all dependencies before running
before_script:
  - npm install

# check code style issues
linting:
  stage: concurChecks
  only:
    - main
    - merge_requests
  script:
    - echo "Linting code..."
    - npx eslint . || exit 1

# check if build passes all unit tests
testing:
  stage: concurChecks
  only:
    - main
    - merge_requests
  script:
    - echo "Running unit tests..."
    - npm test
    # TODO

# Deploys everything in the main branch to serverless endpoint
deploying:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying application to AWS Lambda..."
    # TODO
