# This file is used for continuous integration

# add an image below later if needed
image: node:20-alpine

stages:
  # tests concurrently with lint and unit tests
  - concurChecks
  - deploy

# install all dependencies before running
before_script:
  - npm install

# check code style issues
linting:
  stage: concurChecks
  only:
    - main
    - merge_requests
  script:
    - echo "Linting code..."
    - npx eslint . || exit 1

# check if build passes all unit tests
testing:
  stage: concurChecks
  only:
    - main
    - merge_requests
  script:
    - echo "Running unit tests..."
    - npm test

# Deploys everything in the main branch to serverless endpoint
deploy_production:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - echo "Deploying to vercel frontend"
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

    - echo "Deploying application to AWS Lambda..."
    # Left for later, want to deploy manually atm
