# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "Breadstackers-AWS"
region = "ap-southeast-2"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
stack_name = "BreadStackersFinalOrderCreateApi"
s3_prefix = "BreadStackersFinalOrderCreateApi"
image_repositories = []
parameter_overrides = "JWTSecretParameter=\"adb67e02cdbb535b5b10651043123bb5ba247e8c60553756476809cca20efba7\" SupabaseUrl=\"https://azqivhutrngckrujulyf.supabase.co\" SupabaseKey=\"sb_secret_KajMXbDwm-2WRAIhfOLtVg_toido4BW\""

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
