AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Breadstackers-AWS
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:

  placeHolderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/placeholder.handlers
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/health
            Method: GET

# Add handlers here whenever you create a new Lambda, see the template below. Make sure y'all remove the '{}' too:

createOrderFunction:
  Type: AWS::Serverless::Function
  Properties:
    Handler: src/handlers/createOrder.createOrderHandler
    Events:
      Api:
        Type: Api
        Properties:
          Path: /api/orders
          Method: POST

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    MemorySize: 128
    Timeout: 30
    LoggingConfig:
      LogFormat: JSON
