AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Breadstackers-AWS
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:

  BreadStackersApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: BreadStackersPlan
          # Usage limits - change if needed
          Throttle: 
            # 10 reqs/s
            RateLimit: 10
            # 20 reqs at once
            BurstLimit: 20
          Quota:
            # 1000 reqs/day
            Limit: 1000
            Period: DAY

  placeHolderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/placeholder.dummyHandler
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref BreadStackersApi
            Path: /api/health
            Method: GET

  cancelOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/cancelOrder.cancelOrderHandler
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref BreadStackersApi
            Path: /v0/order/{orderId}
            Method: DELETE

  
# Add handlers here whenever you create a new Lambda, see the template below. Make sure y'all remove the '{}' too:

  createOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/placeholder.createOrderHandler
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref BreadStackersApi
            Path: /v0/order
            Method: POST
  
  getOrderInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/orderInfo.getOrderInfoHandler
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref BreadStackersApi
            Path: /v0/order/{orderId}
            Method: GET
  
  userRegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/userRegister.registerUserHandler
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref BreadStackersApi
            Path: /v0/user/register
            Method: POST
  
  userLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/userLogin.userLoginHandler
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref BreadStackersApi
            Path: /v0/user/login
            Method: POST
  
  userDetailsUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/userDetails.updateUserDetailsHandler
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref BreadStackersApi
            Path: /v0/user/details
            Method: PUT
  
  userLogoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/userLogout.userLogoutHandler
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref BreadStackersApi
            Path: /v0/user/logout
            Method: POST

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${BreadStackersApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    MemorySize: 128
    Timeout: 30
    LoggingConfig:
      LogFormat: JSON
